name: gootsmoji build

on:
  push:
    branches: ["main"]
    paths:
      - goots/**
  pull_request:

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install dependencies
        run: |
          uv sync

      - name: Build Assets
        run: |
          uv run build.py

      - name: Update built assets
        if: github.ref == 'refs/heads/main'
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
            git config user.name 'github-actions[bot]'
            git commit --all --message='Automatic Asset Rebuild'
            git push
          fi
